[package]
name = "AutoShortcut"
version = "2.4.0"
edition = "2024"

[build-dependencies]
embed-resource = "3.0.11"
thunk-rs = "0.3.5"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dev-dependencies]
tempfile = "3.27.0"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"
clap = { version = "4.6.6", features = ["derive"] }
console = "0.16.4"
walkdir = "2.5.0"
csv = "1.4.0"
aho-corasick = "1.1.5"
glob = "0.3.4"
goblin = "0.10.7"
memmap2 = "0.9.11"
rust-i18n = "4.2.2"
sys-locale = "0.3.2"
chrono = "0.4.45"
anyhow = "1.0.104"
windows = { version = "0.62.2", features = ["Win32_Storage_FileSystem", "Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_SystemInformation", "Win32_System_Diagnostics", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading", "Win32_System_Com", "Win32_System_Console"] }
