"""Generate src/model/generated_xgboost.rs from a trained model bundle."""

from __future__ import annotations

import argparse
import json
import re
import struct
from pathlib import Path

import joblib
import m2cgen as m2c

from train import FEATURE_NAMES, FEATURE_SCHEMA_VERSION


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("model_bundle", type=Path)
    parser.add_argument("rust_output", type=Path)
    parser.add_argument("--parity-output", type=Path)
    args = parser.parse_args()
    bundle = joblib.load(args.model_bundle)
    if bundle.get("feature_schema_version") != FEATURE_SCHEMA_VERSION:
        raise RuntimeError("model bundle feature schema version does not match the Rust schema")
    if bundle.get("feature_names") != FEATURE_NAMES:
        raise RuntimeError("model bundle feature names/order do not match the Rust schema")
    if not all(0.0 <= float(bundle[name]) <= 1.0 for name in ("min_top_probability", "min_probability_margin")):
        raise RuntimeError("model thresholds must be finite values in [0, 1]")
    code = m2c.export_to_rust(bundle["model"], function_name="score")
    if not re.search(r"\bfn\s+score\s*\(input:\s*Vec<f64>\)\s*->\s*Vec<f64>", code):
        raise RuntimeError("M2CGen output does not match fn score(input: Vec<f64>) -> Vec<f64>")
    code = re.sub(r"\bfn\s+score\s*\(", "pub fn score(", code, count=1)
    split_pattern = re.compile(r"(if input\[\d+\] (?:<|>=) )([-+0-9.eE]+)_f64")

    def exact_float32_threshold(match: re.Match[str]) -> str:
        value = struct.unpack("<f", struct.pack("<f", float(match.group(2))))[0]
        return f"{match.group(1)}{value:.17g}_f64"

    code, split_count = split_pattern.subn(exact_float32_threshold, code)
    if split_count == 0:
        raise RuntimeError("M2CGen output did not contain any XGBoost split thresholds")
    header = f'''// Generated by training/generate_model.py. Do not edit by hand.
pub const MODEL_AVAILABLE: bool = true;
pub const MODEL_FEATURE_SCHEMA_VERSION: u32 = {int(bundle["feature_schema_version"])};
pub const MODEL_FEATURE_COUNT: usize = {len(bundle["feature_names"])};
pub const MODEL_MIN_TOP_PROBABILITY: f64 = {float(bundle["min_top_probability"]):.17g};
pub const MODEL_MIN_PROBABILITY_MARGIN: f64 = {float(bundle["min_probability_margin"]):.17g};

'''
    args.rust_output.parent.mkdir(parents=True, exist_ok=True)
    args.rust_output.write_text(header + code, encoding="utf-8")
    if args.parity_output:
        args.parity_output.parent.mkdir(parents=True, exist_ok=True)
        args.parity_output.write_text(
            json.dumps(
                {
                    "feature_schema_version": bundle["feature_schema_version"],
                    "cases": bundle.get("parity_cases", []),
                },
                indent=2,
            ),
            encoding="utf-8",
        )
    print(args.rust_output)


if __name__ == "__main__":
    main()
